// Code generated by entc, DO NOT EDIT.

package zone

const (
	// Label holds the string label denoting the zone type in the database.
	Label = "zone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the zone in the database.
	Table = "zones"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "zones"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_zones"
)

// Columns holds all SQL columns for zone fields.
var Columns = []string{
	FieldID,
	FieldDomain,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "zones"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_zones",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
