// Code generated by entc, DO NOT EDIT.

package zone

const (
	// Label holds the string label denoting the zone type in the database.
	Label = "zone"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the zone in the database.
	Table = "zones"
)

// Columns holds all SQL columns for zone fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
