// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/blahcdn/db/ent/zone"
)

// Zone is the model entity for the Zone schema.
type Zone struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Zone) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case zone.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Zone", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Zone fields.
func (z *Zone) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case zone.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			z.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Zone.
// Note that you need to call Zone.Unwrap() before calling this method if this Zone
// was returned from a transaction, and the transaction was committed or rolled back.
func (z *Zone) Update() *ZoneUpdateOne {
	return (&ZoneClient{config: z.config}).UpdateOne(z)
}

// Unwrap unwraps the Zone entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (z *Zone) Unwrap() *Zone {
	tx, ok := z.config.driver.(*txDriver)
	if !ok {
		panic("ent: Zone is not a transactional entity")
	}
	z.config.driver = tx.drv
	return z
}

// String implements the fmt.Stringer.
func (z *Zone) String() string {
	var builder strings.Builder
	builder.WriteString("Zone(")
	builder.WriteString(fmt.Sprintf("id=%v", z.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Zones is a parsable slice of Zone.
type Zones []*Zone

func (z Zones) config(cfg config) {
	for _i := range z {
		z[_i].config = cfg
	}
}
