// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blahcdn/db/ent/predicate"
	"github.com/blahcdn/db/ent/zone"
)

// ZoneDelete is the builder for deleting a Zone entity.
type ZoneDelete struct {
	config
	hooks    []Hook
	mutation *ZoneMutation
}

// Where adds a new predicate to the ZoneDelete builder.
func (zd *ZoneDelete) Where(ps ...predicate.Zone) *ZoneDelete {
	zd.mutation.predicates = append(zd.mutation.predicates, ps...)
	return zd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (zd *ZoneDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(zd.hooks) == 0 {
		affected, err = zd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ZoneMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			zd.mutation = mutation
			affected, err = zd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(zd.hooks) - 1; i >= 0; i-- {
			mut = zd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, zd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (zd *ZoneDelete) ExecX(ctx context.Context) int {
	n, err := zd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (zd *ZoneDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: zone.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: zone.FieldID,
			},
		},
	}
	if ps := zd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, zd.driver, _spec)
}

// ZoneDeleteOne is the builder for deleting a single Zone entity.
type ZoneDeleteOne struct {
	zd *ZoneDelete
}

// Exec executes the deletion query.
func (zdo *ZoneDeleteOne) Exec(ctx context.Context) error {
	n, err := zdo.zd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{zone.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (zdo *ZoneDeleteOne) ExecX(ctx context.Context) {
	zdo.zd.ExecX(ctx)
}
